server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sonpexel@gmail.com
    password: oiekkyvlpnjyyaid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: "jdbc:mysql://localhost:3306/ltdd"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


vnp_TmnCode: AYSYO0AR
vnp_HashSecret: MRNCERENKB1A3UNI3NXJ7OQ0P2R9PZ4P
vnp_Url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnUrl: https://6f2f-42-113-218-65.ngrok-free.app/api/vnpay/return
vnp_IpnUrl: https://6f2f-42-113-218-65.ngrok-free.app/api/vnpay/ipn

